In [1]:
## Pytorch fundamental Tensor Fundamentals

In [2]:
print ("This is my first goole program")

This is my first goole program


In [3]:
!nvidia-smi

Sat Jul 26 18:18:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
print (torch.__version__)

2.6.0+cu124


In [5]:
## Introduction to Tensor

# Scalar

scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

# Vector
vector = torch.tensor([8, 8])
print(vector)
print(vector.ndim)
print(vector.shape)

# matrix
matrix = torch.tensor([ [1, 2, 2],
                        [3, 4, 3],
                        [5, 6, 8],
                        [2, 4, 5]])

print(matrix)
print("dimension = ", matrix.ndim)
print("shape = ", matrix.shape)
print(" matrix[0] = ", matrix[0])
print(" matrix[0][0] = ", matrix[0][0])
print(" matrix[0][0].item() = ", matrix[0][0].item())
print(" matrix[1] = ", matrix[1])

### Creating Tensors

tensor(7)
0
7
tensor([8, 8])
1
torch.Size([2])
tensor([[1, 2, 2],
        [3, 4, 3],
        [5, 6, 8],
        [2, 4, 5]])
dimension =  2
shape =  torch.Size([4, 3])
 matrix[0] =  tensor([1, 2, 2])
 matrix[0][0] =  tensor(1)
 matrix[0][0].item() =  1
 matrix[1] =  tensor([3, 4, 3])


In [6]:
TENSOR = torch.tensor([[ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]],
                       [ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]],
                       [ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]],
                       [ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]]
                      ])
print(TENSOR)
print("dimension = ", TENSOR.ndim)
print("shape = ", TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]]])
dimension =  3
shape =  torch.Size([4, 4, 3])


In [7]:
### Random Tensor
RANDOM_TENSOR = torch.rand(3, 4, 6, 7)
print(RANDOM_TENSOR)
print("dimension = ", RANDOM_TENSOR.ndim)
print("shape = ", RANDOM_TENSOR.shape)

tensor([[[[0.3130, 0.2867, 0.6386, 0.2674, 0.3201, 0.6729, 0.9988],
          [0.2582, 0.6320, 0.5355, 0.9253, 0.9853, 0.0965, 0.2433],
          [0.2685, 0.9189, 0.9426, 0.0492, 0.1385, 0.5816, 0.8072],
          [0.6673, 0.9216, 0.5647, 0.2512, 0.5174, 0.0101, 0.2436],
          [0.4922, 0.5328, 0.0293, 0.6707, 0.2628, 0.9251, 0.0299],
          [0.9149, 0.3899, 0.5104, 0.0109, 0.2242, 0.7929, 0.6767]],

         [[0.7086, 0.2870, 0.0402, 0.2089, 0.1597, 0.4982, 0.2182],
          [0.0486, 0.9167, 0.6117, 0.5206, 0.4368, 0.6891, 0.2609],
          [0.7343, 0.5967, 0.2959, 0.3167, 0.3923, 0.2348, 0.4806],
          [0.6080, 0.8020, 0.4640, 0.3081, 0.2772, 0.4390, 0.5253],
          [0.6794, 0.6166, 0.1285, 0.6878, 0.0376, 0.5084, 0.9795],
          [0.4964, 0.3802, 0.8309, 0.3115, 0.0448, 0.1691, 0.3951]],

         [[0.2506, 0.0933, 0.5658, 0.8922, 0.6111, 0.7799, 0.4773],
          [0.1241, 0.8461, 0.0883, 0.7998, 0.9711, 0.1930, 0.6929],
          [0.9274, 0.7446, 0.2721, 0.3139, 0

In [8]:
TENSOR_RANDOM_VECOR = torch.rand(3)
print(TENSOR_RANDOM_VECOR)
print("dimension = ", TENSOR_RANDOM_VECOR.ndim)
print("shape = ", TENSOR_RANDOM_VECOR.shape)

tensor([0.5568, 0.5156, 0.1818])
dimension =  1
shape =  torch.Size([3])


In [9]:
TENSOR_RANDOM_MATRIX = torch.rand(3, 4)
print(TENSOR_RANDOM_MATRIX)
print("dimension = ", TENSOR_RANDOM_MATRIX.ndim)
print("shape = ", TENSOR_RANDOM_MATRIX.shape)

tensor([[0.8528, 0.1202, 0.7525, 0.8128],
        [0.1402, 0.7622, 0.0503, 0.1856],
        [0.8355, 0.9745, 0.3790, 0.1624]])
dimension =  2
shape =  torch.Size([3, 4])


In [10]:
## Create an image Tensor. Image has Color (RGB), height and width
IMAGE_TENSOR = torch.rand(224, 224, 3)
print(IMAGE_TENSOR)
print("dimension = ", IMAGE_TENSOR.ndim)
print("shape = ", IMAGE_TENSOR.shape)

tensor([[[0.2415, 0.3940, 0.4955],
         [0.3533, 0.9655, 0.5482],
         [0.7107, 0.2764, 0.9302],
         ...,
         [0.0243, 0.6932, 0.5530],
         [0.7045, 0.7321, 0.9265],
         [0.9524, 0.7786, 0.7403]],

        [[0.7662, 0.1282, 0.0435],
         [0.9624, 0.9296, 0.9268],
         [0.8507, 0.7944, 0.3344],
         ...,
         [0.7600, 0.3298, 0.1074],
         [0.7109, 0.7452, 0.2795],
         [0.5285, 0.5147, 0.4391]],

        [[0.4004, 0.3392, 0.3193],
         [0.5617, 0.9505, 0.7260],
         [0.3316, 0.6089, 0.1654],
         ...,
         [0.7853, 0.6129, 0.8901],
         [0.2073, 0.2561, 0.5119],
         [0.8100, 0.6840, 0.1275]],

        ...,

        [[0.7863, 0.1868, 0.8534],
         [0.5522, 0.1866, 0.7799],
         [0.2565, 0.3445, 0.3480],
         ...,
         [0.2592, 0.4526, 0.8129],
         [0.6965, 0.9346, 0.5575],
         [0.7249, 0.7632, 0.6868]],

        [[0.2335, 0.3253, 0.8207],
         [0.3608, 0.9737, 0.1043],
         [0.

In [11]:
# Tesnors with Zeros
ZERO_TENSOR = torch.zeros(3, 4)
print(ZERO_TENSOR)
print("dimension = ", ZERO_TENSOR.ndim)
print("shape = ", ZERO_TENSOR.shape)



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
dimension =  2
shape =  torch.Size([3, 4])


In [12]:
# Tensors with Ones
ONES_TENSOR = torch.ones(3, 4)
print(ONES_TENSOR)
print("dimension = ", ONES_TENSOR.ndim)
print("shape = ", ONES_TENSOR.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
dimension =  2
shape =  torch.Size([3, 4])


In [13]:
### Torch Range

RANGE = torch.arange(0, 10)
print(RANGE)
print("dimension = ", RANGE.ndim)
print("shape = ", RANGE.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
dimension =  1
shape =  torch.Size([10])


In [14]:
RANGE = torch.arange(2, 30000 , 100)
print(RANGE)
print("dimension = ", RANGE.ndim)
print("shape = ", RANGE.shape)


tensor([    2,   102,   202,   302,   402,   502,   602,   702,   802,   902,
         1002,  1102,  1202,  1302,  1402,  1502,  1602,  1702,  1802,  1902,
         2002,  2102,  2202,  2302,  2402,  2502,  2602,  2702,  2802,  2902,
         3002,  3102,  3202,  3302,  3402,  3502,  3602,  3702,  3802,  3902,
         4002,  4102,  4202,  4302,  4402,  4502,  4602,  4702,  4802,  4902,
         5002,  5102,  5202,  5302,  5402,  5502,  5602,  5702,  5802,  5902,
         6002,  6102,  6202,  6302,  6402,  6502,  6602,  6702,  6802,  6902,
         7002,  7102,  7202,  7302,  7402,  7502,  7602,  7702,  7802,  7902,
         8002,  8102,  8202,  8302,  8402,  8502,  8602,  8702,  8802,  8902,
         9002,  9102,  9202,  9302,  9402,  9502,  9602,  9702,  9802,  9902,
        10002, 10102, 10202, 10302, 10402, 10502, 10602, 10702, 10802, 10902,
        11002, 11102, 11202, 11302, 11402, 11502, 11602, 11702, 11802, 11902,
        12002, 12102, 12202, 12302, 12402, 12502, 12602, 12702, 

In [17]:
# tensors like
TENSOR_LIKE = torch.zeros_like(RANGE)
print(TENSOR_LIKE)
print("dimension = ", TENSOR_LIKE.ndim)
print("shape = ", TENSOR_LIKE.shape)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [22]:
# Tensor Data Types

float32_dtype_tensor = torch.tensor([3.0, 6.0, 9.0],
                                    dtype= None,
                                    device=None,
                                    requires_grad=False)
print(float32_dtype_tensor)
print("dimension = ", float32_dtype_tensor.ndim)
print("shape = ", float32_dtype_tensor.shape)
print("dtype = ", float32_dtype_tensor.dtype)

tensor([3., 6., 9.])
dimension =  1
shape =  torch.Size([3])
dtype =  torch.float32


In [26]:
float16_dtype_tensor = torch.tensor([3.0, 6.0, 9.0],
                                    dtype= torch.float16,
                                    device=None,
                                    requires_grad=False)
print(float16_dtype_tensor)
print("dimension = ", float16_dtype_tensor.ndim)
print("shape = ", float16_dtype_tensor.shape)
print("dtype = ", float16_dtype_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
dimension =  1
shape =  torch.Size([3])
dtype =  torch.float16


In [28]:
TENSOR_MUL= float16_dtype_tensor * float32_dtype_tensor
print(TENSOR_MUL)
print("dimension = ", TENSOR_MUL.ndim)
print("shape = ", TENSOR_MUL.shape)
print("dtype = ", TENSOR_MUL.dtype)

tensor([ 9., 36., 81.])
dimension =  1
shape =  torch.Size([3])
dtype =  torch.float32


In [34]:
int32_dtype_tensor = torch.tensor([3, 6, 9],
                                    dtype= torch.int32,
                                    device=None,
                                    requires_grad=False)
print(int32_dtype_tensor)
print("dimension = ", int32_dtype_tensor.ndim)
print("shape = ", int32_dtype_tensor.shape)
print("dtype = ", int32_dtype_tensor.dtype)

tensor([3, 6, 9], dtype=torch.int32)
dimension =  1
shape =  torch.Size([3])
dtype =  torch.int32


In [30]:
TENSOR_MUL= float16_dtype_tensor * float32_dtype_tensor
print(TENSOR_MUL)
print("dimension = ", TENSOR_MUL.ndim)
print("shape = ", TENSOR_MUL.shape)
print("dtype = ", TENSOR_MUL.dtype)

tensor([ 27., 216., 729.])
dimension =  1
shape =  torch.Size([3])
dtype =  torch.float32


In [31]:
#### Get Information from Tensor

print(TENSOR_MUL)
print("dimension = ", TENSOR_MUL.ndim)
print("shape = ", TENSOR_MUL.shape)
print("dtype = ", TENSOR_MUL.dtype)
print("device = ", TENSOR_MUL.device)

tensor([ 27., 216., 729.])
dimension =  1
shape =  torch.Size([3])
dtype =  torch.float32
device =  cpu
