In [42]:
## Pytorch fundamental Tensor Fundamentals

In [1]:
print ("This is my first goole program")

This is my first goole program


In [2]:
!nvidia-smi

Sat Jul 26 16:09:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch
print (torch.__version__)

2.6.0+cu124


In [40]:
## Introduction to Tensor

# Scalar

scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

# Vector
vector = torch.tensor([8, 8])
print(vector)
print(vector.ndim)
print(vector.shape)

# matrix
matrix = torch.tensor([ [1, 2, 2],
                        [3, 4, 3],
                        [5, 6, 8],
                        [2, 4, 5]])

print(matrix)
print("dimension = ", matrix.ndim)
print("shape = ", matrix.shape)
print(" matrix[0] = ", matrix[0])
print(" matrix[0][0] = ", matrix[0][0])
print(" matrix[0][0].item() = ", matrix[0][0].item())
print(" matrix[1] = ", matrix[1])

### Creating Tensors

tensor(7)
0
7
tensor([8, 8])
1
torch.Size([2])
tensor([[1, 2, 2],
        [3, 4, 3],
        [5, 6, 8],
        [2, 4, 5]])
dimension =  2
shape =  torch.Size([4, 3])
 matrix[0] =  tensor([1, 2, 2])
 matrix[0][0] =  tensor(1)
 matrix[0][0].item() =  1
 matrix[1] =  tensor([3, 4, 3])


In [41]:
TENSOR = torch.tensor([[ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]],
                       [ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]],
                       [ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]],
                       [ [1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9],
                         [7, 8, 9]]
                      ])
print(TENSOR)
print("dimension = ", TENSOR.ndim)
print("shape = ", TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [7, 8, 9]]])
dimension =  3
shape =  torch.Size([4, 4, 3])
