## Tensor operations

In [1]:
# Manipulation Tensors
# addition
# Subtraction
# Multiplication
# division

In [2]:
import torch

In [3]:
# Addition
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([[4,5,6], [7,8,9], [1,1,1]])
tensor_3 = torch.tensor([4,5,6])

tensor_3 = tensor_1 + tensor_2 + tensor_3
print(tensor_3)

tensor_3 = tensor_3 + 10

print(tensor_3)


tensor([[ 9, 12, 15],
        [12, 15, 18],
        [ 6,  8, 10]])
tensor([[19, 22, 25],
        [22, 25, 28],
        [16, 18, 20]])


In [4]:
## Subtraction

print("tensor_3 = ", tensor_3)
print("tensor_2 = ", tensor_2)
print("tensor_1 = ", tensor_1)


print("tensor_3 -10 = ", tensor_3 - 10)

print("tensor_3 - 10 - tensor_2 = ", tensor_3 - 10 - tensor_2)

print("tensor_3 - 10 - tensor_2 - tensor_1 = ", tensor_3 - 10 - tensor_2 - tensor_1)




tensor_3 =  tensor([[19, 22, 25],
        [22, 25, 28],
        [16, 18, 20]])
tensor_2 =  tensor([[4, 5, 6],
        [7, 8, 9],
        [1, 1, 1]])
tensor_1 =  tensor([1, 2, 3])
tensor_3 -10 =  tensor([[ 9, 12, 15],
        [12, 15, 18],
        [ 6,  8, 10]])
tensor_3 - 10 - tensor_2 =  tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])
tensor_3 - 10 - tensor_2 - tensor_1 =  tensor([[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]])


In [5]:
## Multiply

print("tensor_3 = ", tensor_3)
print("tensor_2 = ", tensor_2)
print("tensor_1 = ", tensor_1)

# print("tensor_3 *10 = ", tensor_3 * 10)

print("tensor_3 * tensor_2 = ", tensor_3 * tensor_2)


print("tensor_3 * tensor_1 = ", tensor_3 * tensor_1)


tensor_3 =  tensor([[19, 22, 25],
        [22, 25, 28],
        [16, 18, 20]])
tensor_2 =  tensor([[4, 5, 6],
        [7, 8, 9],
        [1, 1, 1]])
tensor_1 =  tensor([1, 2, 3])
tensor_3 * tensor_2 =  tensor([[ 76, 110, 150],
        [154, 200, 252],
        [ 16,  18,  20]])
tensor_3 * tensor_1 =  tensor([[19, 44, 75],
        [22, 50, 84],
        [16, 36, 60]])


In [6]:
## divide

print("tensor_3 = ")
print(tensor_3)
print("tensor_2 = ")
print(tensor_2)
print("tensor_1 = ")
print(tensor_1)

print("tensor_3 /10 = ", tensor_3 /10)

print("tensor_3 /tensor 2 = ", tensor_3 /tensor_2)


print("tensor_3 /1+2= ", (tensor_3 /torch.tensor([1,2,3])))

tensor_3 = 
tensor([[19, 22, 25],
        [22, 25, 28],
        [16, 18, 20]])
tensor_2 = 
tensor([[4, 5, 6],
        [7, 8, 9],
        [1, 1, 1]])
tensor_1 = 
tensor([1, 2, 3])
tensor_3 /10 =  tensor([[1.9000, 2.2000, 2.5000],
        [2.2000, 2.5000, 2.8000],
        [1.6000, 1.8000, 2.0000]])
tensor_3 /tensor 2 =  tensor([[ 4.7500,  4.4000,  4.1667],
        [ 3.1429,  3.1250,  3.1111],
        [16.0000, 18.0000, 20.0000]])
tensor_3 /1+2=  tensor([[19.0000, 11.0000,  8.3333],
        [22.0000, 12.5000,  9.3333],
        [16.0000,  9.0000,  6.6667]])


In [7]:
# dot product (matric multiplication)
%%time
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([[1], [2], [3]])

print(tensor_1 , " * ", tensor_2, " = ", torch.matmul(tensor_1, tensor_2))
print("----")
print(tensor_1 , " * ", tensor_2, " = ", torch.mul(tensor_1, tensor_2))

tensor([1, 2, 3])  *  tensor([[1],
        [2],
        [3]])  =  tensor([14])
----
tensor([1, 2, 3])  *  tensor([[1],
        [2],
        [3]])  =  tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])
CPU times: user 989 µs, sys: 1.84 ms, total: 2.82 ms
Wall time: 6.32 ms


In [10]:
tensor_1 = torch.tensor([[1, 2, 3], [2, 4, 5]])


print(tensor_1.mT)

tensor([[1, 2],
        [2, 4],
        [3, 5]])
