## Tensor Aggregation
# min, max, avg

In [6]:
import torch

In [7]:
TENSOR = torch.rand(5, 3 ,4)

print("---------TENSOR---------")
print(TENSOR)
print("---------TENSOR---------")

---------TENSOR---------
tensor([[[0.0866, 0.2542, 0.2335, 0.0929],
         [0.0755, 0.2122, 0.0778, 0.5980],
         [0.3603, 0.6690, 0.8128, 0.2296]],

        [[0.7478, 0.6686, 0.1507, 0.3097],
         [0.8680, 0.6495, 0.7910, 0.0517],
         [0.5594, 0.7504, 0.1396, 0.8109]],

        [[0.8430, 0.9198, 0.4134, 0.2683],
         [0.2357, 0.2250, 0.6621, 0.1330],
         [0.0017, 0.0375, 0.6510, 0.1705]],

        [[0.0606, 0.2016, 0.5988, 0.7576],
         [0.0523, 0.2620, 0.1191, 0.0498],
         [0.3784, 0.0736, 0.5558, 0.4359]],

        [[0.4985, 0.3999, 0.8417, 0.2850],
         [0.6473, 0.0283, 0.7325, 0.1542],
         [0.8810, 0.0739, 0.3043, 0.9736]]])
---------TENSOR---------


In [11]:
print(TENSOR.min())
print(TENSOR.max())
print(TENSOR.mean())
print(TENSOR.mean(dim=0))
print(TENSOR.mean(dim=1))
print(TENSOR.mean(dim=2))
print(TENSOR.mean(dim=0).shape)
print(TENSOR.mean(dim=1).shape)
print(TENSOR.argmin())

tensor(0.0017)
tensor(0.9736)
tensor(0.4021)
tensor([[0.4473, 0.4888, 0.4476, 0.3427],
        [0.3757, 0.2754, 0.4765, 0.1973],
        [0.4362, 0.3209, 0.4927, 0.5241]])
tensor([[0.1741, 0.3785, 0.3747, 0.3068],
        [0.7251, 0.6895, 0.3604, 0.3908],
        [0.3601, 0.3941, 0.5755, 0.1906],
        [0.1638, 0.1791, 0.4245, 0.4144],
        [0.6756, 0.1674, 0.6262, 0.4709]])
tensor([[0.1668, 0.2409, 0.5179],
        [0.4692, 0.5901, 0.5651],
        [0.6111, 0.3140, 0.2152],
        [0.4046, 0.1208, 0.3609],
        [0.5063, 0.3906, 0.5582]])
torch.Size([3, 4])
torch.Size([5, 4])
tensor(32)
