In [14]:
## Reshaping Tensors

In [15]:
import torch


In [16]:
TENSOR = torch.tensor([
    [1, 2,  3,  4,  5, 6, 7, 8],
    [8, 9, 10, 11, 12, 6, 7, 8]])

In [17]:
TENSOR.shape

torch.Size([2, 8])

In [23]:
print (TENSOR.reshape(1, 16))



tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10, 11, 12,  6,  7,  8]])


In [24]:
print (TENSOR.reshape(4, 4))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 10, 11],
        [12,  6,  7,  8]])


In [36]:
torch.stack([ torch.tensor([1,2,3]), torch.tensor([4,5,6]), torch.tensor([7,8,9])], dim=1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [40]:
torch.squeeze(torch.tensor([[[[1,2,3], [3, 4, 5]]]]))

tensor([[1, 2, 3],
        [3, 4, 5]])

In [55]:
torch.unsqueeze(torch.tensor([1, 2, 4]), dim=0)

tensor([[1, 2, 4]])

In [48]:
torch.squeeze(torch.tensor([1, 2, 4]))

tensor([1, 2, 4])

In [56]:
torch.squeeze(torch.tensor([1, 2, 4]), dim=0)

tensor([1, 2, 4])

In [ ]:
print(torch.cuda.is_available())